# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SEAJoQihqkv8EYJ4gtZViWdw0KuOvsK
"""

# api.py
from fastapi import FastAPI, HTTPException
from scoring import score

app = FastAPI()

@app.post("/score")
def score_endpoint(payload: dict):
    try:
        return score(payload)
    except KeyError as e:
        raise HTTPException(status_code=400, detail=f"Missing field: {e}")